### ISSUE TITLE
changes to postgresql.conf happen in too many places

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-postgis#111]
# problem

we copy in a modified postgresql.conf

various scripts also write to postgresql.conf

this results in duplicate and possible different unintended settings 

even within the postgresql.conf in the repo there are multiple duplicate settings to start with (on the original lines and then at the end)

# proposed solution

leave the original postgresql.conf in place (and remove it from this repo) and rely on scipts to modify it

**Comment by NyakudyaA** [comment]
@gubuntu this has already been modified in the branch 9.6 and 10. I will just need to port this to the develop branch. We no longer using the logic to copy a modified postgresql.conf because it is ineffective.

**Comment by gubuntu** [comment]
yes I thought I had fixed that previously. Looks like I wasn't on the 9.6 branch as I thought when I was looking through it on GH. 

Please check that 9.6 and 10 are consistent with develop

I propose you remove the branches for older versions and add one for 11/2.5

And add a note to the readme about the git flow policy - all changes to develop (to work with latest stable combination), then merge to version branches, then make local changes in version branches if necessary.

**Comment by gubuntu** [comment]
if you look in the config files in a deplyed instance you'll see multiple copies of custom configs at the end of the file. Is that from the scripts being run on each restart?

**Comment by NyakudyaA** [comment]
@gubuntu I suppose the restart might be doing that.  I will look into this and rectify. The scripts should only run on an upgrade rather than on restart. Otherwise, they should purge the current settings defined in the conf. 

Our git flow has been wrong all along. We have constantly been applying changes to the 9.6 branch. I only realised that the 10 branch was different to develop. 

So, for now, I am going to merge the 10 branch to develop so that the develop has the latest changes from 10. 

I also propose we delete all other branches that are older than 9.6 as not many people would be using them.  Perhaps this should also apply to GeoServer branches where we should delete branches that are very old.

**Comment by NyakudyaA** [comment]
closed via https://github.com/kartoza/docker-postgis/pull/99/commits/8fc61daab924c4127d7f899821bc8c453a5a9855
