### ISSUE TITLE
Link two volumes, container not start

### ISSUE THREAD

**Issue by floran974** [kartoza/docker-postgis#128]
I try to deploy a container docker-postgis 11  with this command :

```
> docker run -d \
> -v $HOME/postgres_data/data:/var/lib/postgresql \
> -v $HOME/postgres_data/conf:/etc/postgresql/11/main  \
> -p 5433:5432 \
> --name=testpostgis \
> -e POSTGRES_USER="gis" \
> -e POSTGRES_PASS="gis" \
> -e POSTGRES_DBNAME="gis" \
> -d kartoza/postgis:11.0-2.5
```

But when i link the second volume  , the container not restart 
My goal it'  have the possiblility to modify the conf file
 
It's possible to link two volumes ? or what it's the best way to modify the conf files ( postgresql -pg_hba.conf)
Thank you

**Comment by NyakudyaA** [comment]
@floran974 If you need to change the conf files you need to look at https://github.com/kartoza/docker-postgis/blob/develop/setup-conf.sh and put your setting there, Because mounting it as a volume will not work because on each restart those settings specified in the setup-conf.sh will overwrite what is in your conf file and you need to ensure the permissions are also written for the conf files

**Comment by floran974** [comment]
ok , thank you
