### ISSUE TITLE
Alpine?

### ISSUE THREAD

**Issue by murbanowicz** [kartoza/docker-postgis#185]
By any chance, could you provide alpine builds?

**Comment by NyakudyaA** [comment]
Hi @murbanowicz we would love to do so. If you are willing you could take a dive into it and we can review your PR. It shouldn’t be that difficult

**Comment by Andrew-Chen-Wang** [comment]
@murbanowicz Any updates? @NyakudyaA can you possibly do it? Alpine takes up a lot less space than the current Debian (I think?) version.

I've been developing in cookiecutter-Django's repository for quite some time, but never touched the Docker configurations.

Edit: Sorry, cookiecutter-Django is a huge setup for deploying a web application. If you check out their compose files ({{ cookiecutter.slug etc. }}/local.yml) and their Dockerfile, specifically for Postgres ({{ cookiecutter.slug etc. }}/compose/production/postgres), you can get a better idea. Again, I'm afraid of touching Docker stuff :P

Edit 2: In cookiecutter-django, we apparently use slim-buster instead of buster. Got it working there with the official Postgis repo.

**Comment by NyakudyaA** [comment]
> @murbanowicz Any updates? @NyakudyaA can you possibly do it? Alpine takes up a lot less space than the current Debian (I think?) version.
> 
> I've been developing in cookiecutter-Django's repository for quite some time, but never touched the Docker configurations.
> 
> Edit: Sorry, cookiecutter-Django is a huge setup for deploying a web application. If you check out their compose files ({{ cookiecutter.slug etc. }}/local.yml) and their Dockerfile, specifically for Postgres ({{ cookiecutter.slug etc. }}/compose/production/postgres), you can get a better idea. Again, I'm afraid of touching Docker stuff :P
> 
> Edit 2: In cookiecutter-django, we apparently use slim-buster instead of buster. Got it working there with the official Postgis repo.

Hi @murbanowicz you can take a look at the new image which uses Debian slim. Alternatively, you can get in touch with us we can come up with a small support contract for us to work on this as this has been on our radar but we have no time or resources to  jump into it asap

**Comment by Andrew-Chen-Wang** [comment]
@NyakudyaA Take a look at the postgis/postgis tag. It used to be under mdillon but the Postgis organization took over about a week ago. They offer Alpine based for PostgreSQL 10 I believe. Recommend you take a look at their setup as I've been using their's for a bit now.

**Comment by NyakudyaA** [comment]
Closing this as we don't have the time to do this now unless we get a client requesting this.
