### ISSUE TITLE
How to understand container restart?

### ISSUE THREAD

**Issue by miloskroulik** [kartoza/docker-postgis#20]
I tried to use this container and imported my DB dump into it. However, I encountered strange issues on container restart (copied from stderr):
````
2015-02-04 10:11:22 UTC LOG:  record with zero length at 0/8303BF0
2015-02-04 10:11:23 UTC ERROR:  role "dbuser" already exists
````
Also, it seems that container starts PostgreSQL at least twice, based on stdlog & stderr. In stdlog, I can see 2 listings of tables, the first one mentions default DB (`gis`), the second one my custom DB created in the container.

I try to support my Drupal installation with this container and it seems, that these issues make Drupal forget its DB configuration, which must be created over & over again.

I', using latest version of docker-postgis.

**Comment by timlinux** [comment]
Hi

You need to use a volume if you want the database to be persistent. Alternatively consider using ``--restart=always`` when you run your container. Postgres is indeed started twice - once as a foreground process t initialise the cluster if it does not exist, and again to start the db in daemon mode.

You may also want to consider using fig to manage your configuration easily. Here is an example config for your fig.yml

```
db:
  image: kartoza/postgis
  volumes:
    - ./postgres_data:/var/lib/postgresql
  environment:
    - USERNAME=docker
    - PASS=docker
```

Then run with:

```
fig up -d db
```

That will result in a persistent database (you may need to change the ownership/permissions of the postgres_data dir so that the pg process can write to it).

I'm going to close this because I believe its just a configuration issue with your deployment and not an issue with the docker image.

**Comment by miloskroulik** [comment]
Thanks, but I've done exactly that (just with Crane insted of Fig). I will try to reproduce issue once more and provide you with better report.

**Comment by timlinux** [comment]
Hi @miloskroulik thanks - feel free to reopen this ticket if you have more details.
