### ISSUE TITLE
Please consider changing your tag names

### ISSUE THREAD

**Issue by jcachat** [kartoza/docker-postgis#225]
The reason for my request is this: I run an application in Google Cloud using GKE.  Google likes to randomly restart VMs for maintenance.  Early Sat morning, they did this to the VM running my Postgres instance which is configured to use the "11.0-2.5" tagged image.

This has happened multiple times with no issue.  But for whatever reason (I am still investigating and will post separately if necessary), when it restarted, that image decided to initialize a brand new database in my existing data directory thus wiping out my entire database and taking down my system.

I would like the peace of mind of knowing that the container I have configured is not going to randomly change without my knowledge to an image I have not tested.  Currently, when a new image is updated, you just re-tag it based on the major Postgres & Postgis version.  But it could contain (breaking) changes to the internal startup scripts or a minor Postgres upgrade!

Could you please just add some kind of container version to your tags?  Or is it just required that we all push your container in to our own private repositories so we can do that ourselves to avoid unexpected updates?  This is certainly what I'm going to be doing going forward.  But even still, I would like some kind of better tagging system so I know what I'm looking at.

It would also be nice if the minor version of Postgres was part of the tag.  I have no idea which one is in the container until I pull it down and start it up.

I apologize if I seem short.  I really do appreciate all the work that goes in to this container.

**Comment by NyakudyaA** [comment]
Hi @jcachat the main reason why we that has been happening is because of the automated docker builds that we setup. So each time you push to the same repo it will force a rebuild of the same image  in docker hub. To get around once an image has been build we will keep it that way and subsequent builds will be tagged with the version number. This is already in place with the 12 image. For the 11 image I will do the same. You should be running automated backups in production anyway.

The main change that came up was the cluster initialization changed to accommodate locale generation.

You now need to pass the env variable 
EXISTING_DATA_DIR=true

Look in the readme.

Will tag another image

**Comment by slhck** [comment]
I would just like to chime in and support this request. I was hit by the same issue, luckily just in a development environment, but for sure it is unexpected, if not dangerous, to push breaking changes (particularly ones that destroy data per default) under the exact same tag name.

Please consider pushing revisions at least with different patch versions, such that end users can properly pin the requirements.

Edit: Tangential to this, but still relevant: It would have made much more sense to add a new environment variable that explicitly asks for destroying/reinitializing existing data, rather than the other way round. Particularly if people are not expecting to get a breaking change delivered.

**Comment by NyakudyaA** [comment]
Fixed the main issues and added a clear description
