### ISSUE TITLE
Newer docker is defaulting to erasing data in older docker!

### ISSUE THREAD

**Issue by jcachat** [kartoza/docker-postgis#226]
On 2/15, a change was made to setup_database.sh that changed how it was determined if the data directory should be initialized from a check to see if it was empty (or didn't exist) to just checking to see if it contained a file named ".postgresql.init.lock".  

Then on 2/25, that check was prevented by checking for the new environment variable EXISTING_DATA_DIR.

Did anyone consider that people didn't know they needed to add that brand new environment variable to their settings?  And that the previous docker versions did not create a ".postgresql.init.lock" file in the data directory????

You basically defaulted to re-initializing a populated data directory unless a brand new environment variable had not been set.  And considering that dockers just download themselves when they are re-started, how can that be safe?  This is what resulted in my request #225 .

If you are going to add environment variables, can you please use safe defaults that will not cause complete data loss?  Why would you even remove the check to make sure the directory is empty before initializing it?  If there is a need to initialize a non-empty directory, wouldn't it make more sense to require someone to define an environment variable such as "PLEASE_ERASE_MY_VALUABLE_DATA_YES_I_AM_SURE=true"????

**Comment by lucernae** [comment]
Huh, this actually happens with me too! 
I thought I made a wrong setup in my own server myself, but it turns out coming from entrypoint script then.

@NyakudyaA , I think he had a point there. That env variable by default doesn't exists for people who just upgrade the image. So it shouldn't default to deleting the data dir.
I think we should prioritize this issue. I will help make new pull request immediately.

**Comment by NyakudyaA** [comment]
> Huh, this actually happens with me too!
> I thought I made a wrong setup in my own server myself, but it turns out coming from entrypoint script then.
> 
> @NyakudyaA , I think he had a point there. That env variable by default doesn't exists for people who just upgrade the image. So it shouldn't default to deleting the data dir.
> I think we should prioritize this issue. I will help make new pull request immediately.

Hi @lucernae realized that as well,  I think the fix was to solve https://github.com/kartoza/docker-postgis/issues/202 which had to reinitialize the DB with the right cluster permisions. So for now I have maintained the images as they were 11.0-2.5 and 12.0 with the old settings and published new images 12.1 and 11.5-2.5

**Comment by NyakudyaA** [comment]
This has been fixed in develop and image 12.1
