### ISSUE TITLE
"No such file or directory" error when executing against latest image version

### ISSUE THREAD

**Issue by efrees** [kartoza/docker-postgis#232]
**Problem**
My team has a build that started failing shortly after the release to Docker Hub today (2020-04-14). The problem is the command below, which uses a relative path to locate a script that was copied into the container with `docker cp`.

```
docker exec test-postgres psql "$PG_CONNECTION_STRING" -f ConfigureDatabase.sql
```

This gives the error `psql: error: ConfigureDatabase.sql: No such file or directory`

**Version**
The command works on tag `:12.1`, but fails on `:latest`. I believe this is due to the WORKDIR being set to the /scripts folder in the updated dockerfile.

**Workaround**
The easy workaround is to use an absolute path instead (i.e., `/ConfigureDatabase.sql`). This is a good solution for me, but I wanted to log this for others' benefit and in case the change in WORKDIR was an oversight.

Many thanks for your work on this image!

**Comment by lucernae** [comment]
Thank you for submitting this.
We changed `WORKDIR` due to refactoring entrypoint related scripts.
At the moment, we haven't decided yet if this is a breaking changes or not. We can keep the workdir in previous location (root directory) and keep the scripts in `/scripts`  folder. But any downstream scripts that use entrypoint scripts should then refer to this locations in future tagged image. (Or maybe we should make it somehow that the scripts is in the shell PATH list).

Just some suggestion for me, to make your usage here more portable, add your expected working directory when running downstream usages such as:

(for relative path)
```
docker exec --workdir=/ test-postgres psql "$PG_CONNECTION_STRING" -f ConfigureDatabase.sql
```

(for absolute path, this is better and removes ambiguity)
```
docker exec test-postgres psql "$PG_CONNECTION_STRING" -f /ConfigureDatabase.sql
```

Because in this case we couldn't guarantee where you will store those scripts, you had to use one of the pattern above.
If you are following our usage pattern, any entrypoint scripts that will be run before the database is exposed to the world must be put in this directory:

https://github.com/kartoza/docker-postgis#running-sql-scripts-on-container-startup

**Comment by efrees** [comment]
Using an absolute path works for me (and I agree it's clearer).
I'm also glad to know about the documented entrypoint pattern, which may come in handy for future cases. I've missed that before. Thanks for the link!

**Comment by lucernae** [comment]
I will close this then.
