### ISSUE TITLE
Mention locales in README

### ISSUE THREAD

**Issue by nilsnolde** [kartoza/docker-postgis#237]
While building the `manual-build` for writing the tests, I realized that by default **all** possible locales are installed, which takes forever and consumes lots of unnecessary space.

Can we either 
- mention in the README prominently that `scripts/locale.gen` needs to be adapted to whatever one wants to have
- ~~make that a build arg, e.g. a list of locales, like `POSTGRES_MULTIPLE_EXTENSIONS`~~ likely not feasible without lots of effort
?

**Comment by nilsnolde** [comment]
And forgive me in case it's actually in the README and I just didn't catch it..

**Comment by NyakudyaA** [comment]
> And forgive me in case it's actually in the README and I just didn't catch it..

Do you have any idea how we could activate the different locales as env variable because they need to be installed on the host. 

It is not mentioned in the readme about building locales. Maybe you could explain that a user can modify the locale.gen during building but this will affect him/her on how to initialize them with env variables.

Alternatively, we can move the logic to entry point and only install the locale that has been specified as env variable if it works

**Comment by nilsnolde** [comment]
Yeah, that's why I crossed out the second alternative. I'd be easy if it was just one ID (like COLLATION), but it's also the ISO code (or whatever that is..). 

So, I can put it in the README. Anyone changing the collation or similar should be aware that the host needs the specified locale, I think that'd be an alright approach for now.

If anyone has an idea how to integrate this better, all ears:)

**Comment by nilsnolde** [comment]
Oops, this wasn't supposed to be closed.. the line `I'll fix #237 when this is merged.` apparently triggered it. stupid..

Anyways, I just created another PR for that.
