### ISSUE TITLE
Run the container as non root

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/docker-postgis#245]
# Problem

The container runs as root and this is generally not encouraged because of the security implications in docker.

When running initdb we also run should also pass the user to this. 

Currently we do a lot of the logic using postgres user. 

# Solution

* Use gosu 
* add a dedicated user for the dB 
* use nsswrapper to navigate some of the user issues 

https://github.com/kartoza/docker-postgis/issues/198

cc @lucernae

**Comment by lucernae** [comment]
I agree with this and consider it in the past, but some part that I can't figure out how to solve:

1. If we run the container as non root, we can't do some management scripts that runs as root. For example, changing permissions of ssl directory/datadir, deleting/creating initdir
2. Running the container as non root will lock the shell inside to only be able to use that user because we shouldn't provide root escalation. You can't modify the container from the inside. You can't install packages/editor. This will seriously affect how you debug the image in development phase.
3. Docker can't fix the permissions if the volume we mount have different permissions than the one the container expects. We have to fix it from outside the lifecycle (manually mounting the volume then change the permissions/ownerships using other container).

Some comments on your proposed solutions:

- Use gosu

I think the proposed approach using gosu looks good. We can use gosu just at the end of entrypoint script to drop privileges. Can we add a flag called RUN_AS_ROOT to allow us running the container as root when we need to? Because once we are dropped into non root, we can't go being root again, we have to restart container with different settings.

- Add a dedicated user for the db

I'm against this approach if we want to address security implications. I would like to have some distinctions between db user and unix user that runs the db. We should think that unix user and db user are independent. If we drop privilege using gosu, it's best to do it with any random unix user not related with the db user (not a dedicated one). But we specify the main db super user, create the role, change pg_hba.conf, etc, before dropping into gosu. This way, you can only login to the db using the db super user credentials (which must specify password). We should not allow login via psql by just using the unix user alone (via trust credentials). If we let container-user log in to psql without password (via trust credentials), there's no point of using gosu.

- Use nsswrapper to navigate some of the user issues

I'm not aware of the possible user issues, maybe you can mention what kind of issues that this will solve. I only thought nsswrapper is just for the cosmetics (so the random UID can have a name). I have neutral opinion in this. The point of running the container as non root means we are not able to do anything significant from inside the container (because we want it to not be able to do anything), so for me there's no point in going inside the container (and uses nsswrapper) if the container is in non-root mode.

# Conclusions

Based on proposed solusions, I think gosu will solve problem 1. But it's not going to fix 2. and 3.
I propose we use gosu, but add the toggle `RUN_AS_ROOT` with default value true for backward compatibility. In addition to that we also need to delete all credentials information inside the container, such as:

`POSTGRES_PASS` environment variable needs to be unset before dropping to gosu. But maybe gosu does clean up current environment variable, we have to check. In that case, we don't need to unset it manually.

`/tmp/credentials.txt`, we don't need this file exists at all.

**Comment by NyakudyaA** [comment]
> I agree with this and consider it in the past, but some part that I can't figure out how to solve:
> 
>     1. If we run the container as non root, we can't do some management scripts that runs as root. For example, changing permissions of ssl directory/datadir, deleting/creating initdir

gosu might be the option here.
> 
>     2. Running the container as non root will lock the shell inside to only be able to use that user because we shouldn't provide root escalation. You can't modify the container from the inside. You can't install packages/editor. This will seriously affect how you debug the image in the development phase.

True, I experienced this with the geoserver image. So we can drop this option.
> 
>     3. Docker can't fix the permissions if the volume we mount have different permissions than the one the container expects. We have to fix it from outside the lifecycle (manually mounting the volume then change the permissions/ownerships using other container).

docker permissions have always been a pain. I think we can just take the idea of running it as non root out of the equation.
> 
> 
> Some comments on your proposed solutions:
> 
>     * Use gosu
> 
> 
> I think the proposed approach using gosu looks good. We can use gosu just at the end of entrypoint script to drop privileges. Can we add a flag called RUN_AS_ROOT to allow us running the container as root when we need to? Because once we are dropped into non root, we can't go being root again, we have to restart container with different settings.

Let's explore this solution
> 
>     * Add a dedicated user for the db
> 
> 
> I'm against this approach if we want to address security implications. I would like to have some distinctions between db user and unix user that runs the db. We should think that unix user and db user are independent. If we drop privilege using gosu, it's best to do it with any random unix user not related with the db user (not a dedicated one). But we specify the main db super user, create the role, change pg_hba.conf, etc, before dropping into gosu. This way, you can only login to the db using the db super user credentials (which must specify password). We should not allow login via psql by just using the unix user alone (via trust credentials). If we let container-user log in to psql without password (via trust credentials), there's no point of using gosu.
> 
>     * Use nsswrapper to navigate some of the user issues
> 
> 
> I'm not aware of the possible user issues, maybe you can mention what kind of issues that this will solve. I only thought nsswrapper is just for the cosmetics (so the random UID can have a name). I have neutral opinion in this. The point of running the container as non root means we are not able to do anything significant from inside the container (because we want it to not be able to do anything), so for me there's no point in going inside the container (and uses nsswrapper) if the container is in non-root mode.

The postgres image allows users to create a cluster using the env POSTGRES_USER. So nsswrapper fakes that there is a user called POSTGRES_USER existing in the image so enabling the user to create and own the cluster. Obviously this would be like having a unix user and database user with the same credentials except that the unix user doen't actually exist.

> # Conclusions
> 
> Based on proposed solusions, I think gosu will solve problem 1. But it's not going to fix 2. and 3.
> I propose we use gosu, but add the toggle `RUN_AS_ROOT` with default value true for backward compatibility. In addition to that we also need to delete all credentials information inside the container, such as:

I thought the point of running the container as non-root is to enable users not to do anything inside the image ie install extra things etc.  However as you mentioned it will be a pain because users cannot be able to run bash scripts because they are not root.
> 
> `POSTGRES_PASS` environment variable needs to be unset before dropping to gosu. But maybe gosu does clean up current environment variable, we have to check. In that case, we don't need to unset it manually.
> 
> `/tmp/credentials.txt`, we don't need this file exists at all.


Yes, we can remove this.

**Comment by rsmith013** [comment]
Are there any updates on this?

**Comment by NyakudyaA** [comment]
> Are there any updates on this?

None, we haven't found time yet but you can also take a stab at it and we will guide you

**Comment by NicolaiLolansen** [comment]
> > Are there any updates on this?
> 
> None, we haven't found time yet but you can also take a stab at it and we will guide you

I would like to take a stab at this. Atleast solving 1) would be a great help for production deployments
