### ISSUE TITLE
SQLi vulnerability in user creation

### ISSUE THREAD

**Issue by camercu** [kartoza/docker-postgis#267]
https://github.com/kartoza/docker-postgis/blob/18f99bc8d65bba72f4f5fe7f63d9e0fa179c73b2/scripts/setup-user.sh#L28

If you try to create a user with a password like `' or 1=1; DROP TABLE pg_roles --` you are going to have a bad day.

**Comment by camercu** [comment]
Practically, this is annoying because I can't have a password that includes the single-quote character (`'`)

**Comment by NyakudyaA** [comment]
@camercu can you provide a patch to ease your frustrations otherwise you could engage with us to provide a solution through https://github.com/kartoza/docker-postgis#support

An alternative solution would be to mount a sql script or bash script https://github.com/kartoza/docker-postgis#running-sql-scripts-on-container-startup  
to create the users until this is resolved.

**Comment by NyakudyaA** [comment]
@camercu can you test the PR that I made otherwise we can close this issue

**Comment by camercu** [comment]
Tested on my machine, and the PR seems to work beautifully!
