### ISSUE TITLE
lock file for startup scripts

### ISSUE THREAD

**Issue by nilsnolde** [kartoza/docker-postgis#294]
I understand why you'd like to have a lock file when using startup scripts (so the sql scripts are not executed multiple times when containers restart I guess?). It does prove a little annoying when you're updating those files, start a fresh container and expect the updated scripts in the new db. Since it's a dot file, it's easy to overlook.

Aside from documenting the lock file:

I know this image already has a ton of (useful) env vars. Would you consider a `UPDATE_SCRIPTS` env var to ignore the lock file worth adding? Would be false by default to not break current behavior. 

Though I'd guess most usages (should) guard against multiple registration with smth similar to `CREATE OR REPLACE` when dealing with functions.

**Comment by nilsnolde** [comment]
I'd PR if you agree (in case that didn't really come out:))

**Comment by NyakudyaA** [comment]
> I'd PR if you agree (in case that didn't really come out:))

I agree you can PR. Do you aim to use the same env var where we are using lockfile or it's just specific to running the SQL scripts

**Comment by nilsnolde** [comment]
Where else are lock files used other than the startup scripts? I'd leave that decision up to you and implement accordingly.

**Comment by NyakudyaA** [comment]
> Where else are lock files used other than the startup scripts? I'd leave that decision up to you and implement it accordingly.

They are used in the following places
https://github.com/kartoza/docker-postgis/blob/develop/scripts/env-data.sh#L323
https://github.com/kartoza/docker-postgis/blob/develop/scripts/setup-database.sh#L82
https://github.com/kartoza/docker-postgis/blob/develop/scripts/setup-pg_hba.sh#L5
https://github.com/kartoza/docker-postgis/blob/develop/scripts/setup-conf.sh#L5

In some other places, I believe we can remove them completely once https://github.com/kartoza/docker-postgis/pull/293/files is merged. But I am happy for you to provide a fix for your immediate concern and we can adapt the logic for the other situations

**Comment by nilsnolde** [comment]
Great thanks @NyakudyaA will PR shortly!

**Comment by lucernae** [comment]
@nilsnolde @NyakudyaA 
Sorry to raise additional comments.
IMHO, since `UPDATE_SCRIPTS` is a term that is not really clear to which scripts it targets to, I propose alternative approach:

1. Create bash helper functions that force rerun startup scripts hook (scripts inside `/docker-entrypoint-initdb.d/`), ignoring the lock file and not setting the lock file. Let's call this for now `exec_startup_hook`. Implement this in `scripts/env-data.sh`
2. Execute `exec_startup_hook` inside `entry_point_script`, reusing the function. But in this `entry_point_script`, check the lock file, and set the lock file when execution finished.

Use case would be:
When you are developing your startup hook and want to re-execute your scripts, do:

```bash
source /scripts/env-data.sh
exec_startup_hook
```

You can re-execute this any number of times as long as you didn't crash the root process (the postgres service).

The benefit from this approach, IMHO:
1. You will need to re-execute the hook anyway, so why not just making it sure that it is the same function that is executed by `entry_point_script` bash function
2. We can be sure that it was sourcing the same `/scripts/env-data.sh` that is used to initialize entrypoint scripts
3. We don't have to maintain extra environment variable --> which means less scenario tests and less sample config to show.

Let us know if this fit your use case.

**Comment by nilsnolde** [comment]
@lucernae I do agree, less conf vars the better. 

I'm a little confused by the suggestion tbh: what you're suggesting would require to actively run a bash function after sourcing the env_data.sh script. From a user perspective, this equals what I'm doing now, `sudo rm .entry_point.lock`. Of course some people might map a single script to the container and never even see the lock file unless `exec`ing into it. In that case your approach would definitely help.

So in the end, I'd be more interested to have the fully automatic approach based on a config. But don't worry, we don't need to  merge this in here, there's a million ways to work around it on my side. I just figured it might be useful in general, but totally understand the maintenance worry!

**Comment by nilsnolde** [comment]
In the no-PR case I'd still PR a README fix to make people aware that there even is a lock file, for exactly that single-file-volume usage where people won't see it.

**Comment by lucernae** [comment]
> I'm a little confused by the suggestion tbh: what you're suggesting would require to actively run a bash function after sourcing the env_data.sh script. From a user perspective, this equals what I'm doing now, sudo rm .entry_point.lock

Ok, maybe I misunderstood the original issue above. Can you clarify here?
Even if you use `UPDATE_SCRIPTS` env var, you still need to execute something after you change your hook scripts in `/docker-entrypoint-initdb.d/`. Probably executing scripts from inside the container like `cat <your sql scripts> | psql ` or `bash <your bash scripts>` or alternatively, restarting the container using `docker restart <container name>`.
In that case, it's the same as doing it via `docker exec <container name> /bin/bash -c "source /scripts/env-data.sh; exec_startup_hook"`

Meanwhile, from your statement here:
> So in the end, I'd be more interested to have the fully automatic approach based on a config.

It seems my proposal does not targeting the problem that you experience. Can you elaborate on this more, please?

**Comment by nilsnolde** [comment]
Well that's true, what I'm proposing wouldn't give you the ability to change anything at runtime. To change behavior you'd still need to create a new container. But the same is true for all other env vars.

So, what I'd like to have is:
I create a container and decide on container creation if my startup scripts should be updated on container restart or not, hence the env var. I think it's valid to issue the same scripts multiple times in most cases, since you'd usually have SQL guarding against already defined functions/procedures etc (`CREATE OR REPLACE` stuff). 

But then yeah, if you decide you don't want that behavior for any reason, you'd need to update the env var and create a new container.

What do you think? Maybe I'm a little lost in my own little world ;)

**Comment by nilsnolde** [comment]
I'm not sure if I made myself clear, but basically if `UPDATE_SCRIPTS=true` (or whatever var name), then simply ignore the lock file for startup scripts.

**Comment by NyakudyaA** [comment]
@lucernae I am in favour of using the env var just like we do for `RECREATE_DATADIR`. We can call this env var a name that people will understand. Your approach although good would mean a user has to exec the container to run the script which I am not in favour of.  

I guess the change would be something like 
```
if [[ ! -f "${SETUP_LOCKFILE}" ]] || [[ "${REPEAT_SCRIPTS}" == 'TRUE' ]]; then
```
Where the env variable defaults to false
I think this change is less invasive

**Comment by lucernae** [comment]
> What do you think? Maybe I'm a little lost in my own little world ;)

No worries! We just want more feedback, that's all. The goal is to make the image easily extensible for special use cases, but also ensure compatibilities. Hence, my proposal aims to provide a hook so the devs can use it from the inside.

Anyway, your comment made it clear that what you actually want is the ability to re-execute the hook scripts on multiple container restarts, ignoring the lock file. I assume, you need this because you possibly have an existing pipeline where other service sends signal via API to restart the container and reapply the hook scripts, CMIIW.

I agree with your approach. But can we change the env variable to reflect what it does better? UPDATE_SCRIPTS seems like a command rather than a flag. We should change it to something like, ALLOW_INIT_HOOK_RERUN or IGNORE_INIT_HOOK_LOCKFILE and set them to False or empty by default as you said.

> I think it's valid to issue the same scripts multiple times in most cases, since you'd usually have SQL guarding against already defined functions/procedures etc (CREATE OR REPLACE stuff).

Yes, I agree. A good dev will make the scripts idempotent. But we can never be sure the user will use it correctly, hence we put the lock file. 

Do you want to target only the lock file inside /docker-entrypoint-initdb.d or others too?

**Comment by lucernae** [comment]
Yes @NyakudyaA , agree with yours too. Your comment's just not loaded when I wrote mine. We just need a more appropriate name that reflects the intention (flag name rather than command). REPEAT and UPDATE is like a command verb to me so I would like to avoid that.

**Comment by nilsnolde** [comment]
Ok cool, thanks to both of you for the immediate attention and the care for maintenance!

I like this one `IGNORE_INIT_HOOK_LOCKFILE` but would make it more specific, maybe `IGNORE_CUSTOM_SQL_LOCKFILE`? Since I think 

> Do you want to target only the lock file inside /docker-entrypoint-initdb.d or others too?

that'd rather be a no from my intuition. It seems it either doesn't really matter, e.g. [cron one](https://github.com/kartoza/docker-postgis/blob/develop/scripts/setup-database.sh#L82), or it would be detrimental for the other PG conf lock files. We can discuss in the PR though, whatever you prefer.

**Comment by NyakudyaA** [comment]
> Ok cool, thanks to both of you for the immediate attention and the care for maintenance!
> 
> I like this one `IGNORE_INIT_HOOK_LOCKFILE` but would make it more specific, maybe `IGNORE_CUSTOM_SQL_LOCKFILE`? Since I think
> 
> > Do you want to target only the lock file inside /docker-entrypoint-initdb.d or others too?
> 
> that'd rather be a no from my intuition. It seems it either doesn't really matter, e.g. [cron one](https://github.com/kartoza/docker-postgis/blob/develop/scripts/setup-database.sh#L82), or it would be detrimental for the other PG conf lock files. We can discuss in the PR though, whatever you prefer.

You can also run `.sh` files so let's not call it `IGNORE_CUSTOM_SQL_LOCKFILE` rather something more inclusive

**Comment by lucernae** [comment]
Just additional comments, the reason I propose IGNORE_**INIT**_HOOK_LOCKFILE is because the lock file is inside /docker-entrypoint-**initdb**.d/, and as @NyakudyaA said it may also process `.sh` files. I'm fine with any flag name as long as it refers to which lockfile it targets (the one in initdb.d) or the phase (startup hook). Since we don't target any other lock file, then it's fine as long as the name contains either one of them :D.

As the famous quote goes, "One of the hardest things in programming is naming things", :laughing: .

Thank you, let's discuss it in the PR.

**Comment by nilsnolde** [comment]
> You can also run .sh files

Oops, that's true, totally forgot about that.. `IGNORE_INIT_HOOK_LOCKFILE` it is then? And should we include .sh scripts to be executed on every container (re)start if the new env var is `true` or is it getting too?

**Comment by lucernae** [comment]
> And should we include .sh scripts to be executed on every container (re)start if the new env var is true or is it getting too?

Yes, `*.sh` and `*.sql` has to be treated the same way. If `*.sql` files can be re-run multiple times, then so does `*.sh`. We want to follow the same convention as what the mainline postgres image is supporting. See https://hub.docker.com/_/postgres under the **Initialization scripts** heading (but ignore the **warning** section, since that's what we want to change in this PR).

CC again @NyakudyaA to reconfirm.

**Comment by NyakudyaA** [comment]
> > And should we include .sh scripts to be executed on every container (re)start if the new env var is true or is it getting too?
> 
> Yes, `*.sh` and `*.sql` has to be treated the same way. If `*.sql` files can be re-run multiple times, then so does `*.sh`. We want to follow the same convention as what the mainline postgres image is supporting. See https://hub.docker.com/_/postgres under the **Initialization scripts** heading (but ignore the **warning** section, since that's what we want to change in this PR).
> 
> CC again @NyakudyaA to reconfirm.

Yes, I confirm
